version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: discord-webhook-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: discord-webhook-manager-dev

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: discord-webhook-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/backend/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/discord-webhook-manager-dev
      - PORT=4000
    depends_on:
      - mongo

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: discord-webhook-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:4000
    depends_on:
      - backend

volumes:
  mongo_data: