version: '3.8'

# Environment Variable Loading Order (later sources override earlier ones):
# 1. App-specific .env files (apps/backend/.env, apps/web/.env)
# 2. Environment variables defined in this file
#
# Setup: 
#   cp apps/backend/.env.example apps/backend/.env
#   cp apps/web/.env.example apps/web/.env
# Then edit the .env files with your credentials (Discord, Cloudinary, etc.)

services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: discord-webhook-manager-dev
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/backend/node_modules
      - pnpm_store:/root/.local/share/pnpm/store
    env_file:
      - apps/backend/.env              # Backend environment variables
    environment:
      # Override for Docker network
      - MONGO_URL=mongodb://mongo:27017/discord-webhook-manager-dev
    depends_on:
      mongo:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - pnpm_store:/root/.local/share/pnpm/store
    env_file:
      - apps/web/.env                  # Web environment variables
    environment:
      # Override for Docker network (web connects to backend via Docker DNS)
      - NEXT_PUBLIC_API_URL=http://backend:4000
      # Enable file watching for hot reload on all platforms
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: pnpm --filter web dev -- --hostname 0.0.0.0 --turbopack
    depends_on:
      - backend

volumes:
  mongo_data:
  pnpm_store: